version: '3.8'

services:
  mariadb:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD : ${ROOT_PASSWORD}
      DATABASE : ${DATABASE_NAME}
    ports:
      - "3307:3307"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 4

  graphql-auth-dev:
    build: ./graphql-auth
